base: 'http://laundryweb.ddev.site/'
baseVariants:
  -
    base: 'http://laundryweb.ddev.site/'
    condition: 'getenv("DDEV_PROJECT") == "laundryWeb"'
errorHandling: {  }
languages:
  -
    title: English
    enabled: true
    base: /en/
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-US
    direction: ''
    flag: en-us-gb
    languageId: '0'
rootPageId: 1
routes:
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\r\nDisallow: /typo3/\r\n"

routeEnhancers:
  Product:
    type: Extbase
    extension: LaundryWebApp
    plugin: LaundryProduct
    defaultController: 'Product::list'
    routes:
      - {_controller: 'Product::list', routePath: '/'}
      - {_controller: 'Product::show', routePath: '/{product}'}
      - {_controller: 'Product::show', routePath: '/{product}/{back}'}
    aspects:
      product:
        type: PersistedAliasMapper
        tableName: 'tx_laundrywebapp_domain_model_product'
        routeFieldName: 'uid'
      back:
        type: StaticValueMapper
        map:
          o: 'overview'
  Overview:
    type: Extbase
    extenstion: LaundryWebApp
    plugin: Overview
    defaultController: 'Dashboard::overview'
    routes:
      - {_controller: 'Dashboard::overview', routePath: '/'}

  Order:
    type: Extbase
    extenstion: LaundryWebApp
    plugin: NewOrder
    defaultController: 'Order::show'
    routes:
      - {_controller: 'Order::show', routePath: '/'}
      - {_controller: 'Order::add', routePath: '/add/{product}'}
      - {_controller: 'Order::remove', routePath: '/remove/{product}'}
      - {_controller: 'Order::purge', routePath: '/purge'}
    aspects:
      product:
        type: PersistedAliasMapper
        tableName: 'tx_laundrywebapp_domain_model_product'
        routeFieldName: 'uid'
      back:
        type: StaticValueMapper
        map:
          o: 'overview'
